server:
  port: 11000

spring:
  application:
    name: coupon
  datasource:
    url: jdbc:mysql://47.104.28.46:23306/sms?
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 78963
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto